"""empty message

Revision ID: 31e609d0c4f9
Revises: 49cd20862975
Create Date: 2023-03-10 23:04:33.516651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31e609d0c4f9'
down_revision = '49cd20862975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gisdocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('docClass', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('localpath', sa.String(), nullable=True),
    sa.Column('webURL', sa.String(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gisDocs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gisDocs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"gisDocs_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('docClass', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('localpath', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('webURL', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gisDocs_pkey')
    )
    op.drop_table('gisdocs')
    # ### end Alembic commands ###
