"""empty message

Revision ID: 6fd37d569375
Revises: 
Create Date: 2023-04-01 20:26:14.709064

"""
from alembic import op
import sqlalchemy as sa
import mapSys.mapSysApp as mapSysApp

# revision identifiers, used by Alembic.
revision = '6fd37d569375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('fid', sa.String(), nullable=False),
    sa.Column('faciName', sa.String(), nullable=True),
    sa.Column('faciDesc', sa.String(), nullable=True),
    sa.Column('faciType', sa.String(), nullable=True),
    sa.Column('featureType', sa.String(), nullable=True),
    sa.Column('geom', mapSysApp.Geometry(), nullable=True),
    sa.PrimaryKeyConstraint('fid')
    )
    op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('route_allsplit', schema=None) as batch_op:
        batch_op.drop_index('route_allsplit_geom_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_allsplit', schema=None) as batch_op:
        batch_op.create_index('route_allsplit_geom_idx', ['geom'], unique=False)

    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('facilities')
    # ### end Alembic commands ###
