"""empty message

Revision ID: c0b7092b5f99
Revises: 
Create Date: 2023-03-10 16:51:49.378314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0b7092b5f99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gisdocument')
    op.drop_table('gisalgorithm')
    op.drop_table('gissample')
    op.drop_table('gisdata')
    op.drop_table('giscase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giscase',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('casename', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('casetype', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('casedesc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('localpath', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weburl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('glocation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='giscase_pkey')
    )
    op.create_table('gisdata',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataname', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('datatype', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('datadesc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('localpath', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weburl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('glocation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gisdata_pkey')
    )
    op.create_table('gissample',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('samname', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('samtype', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('samdesc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('localpath', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weburl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('glocation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gissample_pkey')
    )
    op.create_table('gisalgorithm',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('algname', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('algtype', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('algdesc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('localpath', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weburl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('glocation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gisalgorithm_pkey')
    )
    op.create_table('gisdocument',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('docname', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('doctype', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('docdesc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('localpath', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weburl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('glocation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gisdocument_pkey')
    )
    op.drop_table('cars')
    # ### end Alembic commands ###
